#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

if [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    groupmod -o -g "$PGID" abc
    usermod -o -u "$PUID" abc
fi

echo '
╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io'

if [[ -f /donate.txt ]]; then
    echo "╠═══════════════════════════════╣
  To support this applications developer(s) visit:
  $(cat /donate.txt)"
fi

echo '╠═══════════════════════════════╣
  User/Group ID:'
if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    echo "
  User UID: $(id -u abc)
  User GID: $(id -g abc)"
else
    echo "
  User UID: $(stat /run -c %u)
  User GID: $(stat /run -c %g)
╠═══════════════════════════════╣"
fi
if [[ -f /build_version ]]; then
    echo "╠═══════════════════════════════╣"
    cat /build_version
fi
echo '╚═══════════════════════════════╝'

if [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown abc:abc /app
    lsiown abc:abc /config
    lsiown abc:abc /defaults
fi
    